global:
  scrape_interval: 60s
  scrape_timeout: 60s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "metrics-exporter"
    static_configs:
      - targets: ["metrics-exporter:5000"]
remote_write:
  - url: http://victoria-metrics:8428/api/v1/write
